build_dir: build
content_dir: content
template_dir: templates
context:
  twitter: "pykello"
  github: "pykello"
theorems:
  - name: "theorem"
    label: "Theorem"
  - name: "lemma"
    label: "Lemma"
  - name: "corollary"
    label: "Corollary"
  - name: "proposition"
    label: "Proposition"
  - name: "definition"
    label: "Definition"
  - name: "proof"
    label: "Proof"
    numbered: false
syntax_highlighter_theme: "InspiredGitHub"
escape_markdown_in_math: false
